### ISSUE TITLE
Documentation wrong

### ISSUE THREAD

**Issue by PhilAndrew** [maidsafe-archive/MaidSafe#111]
At the line which says this, it doesn't work for me:

git clone git@github.com:maidsafe/MaidSafe 

orsamac:git orsa$ git clone git@github.com:maidsafe/MaidSafe 
Cloning into 'MaidSafe'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Here
https://github.com/maidsafe/MaidSafe/wiki/Build-Instructions

Phil

**Comment by AnuPGA** [comment]
# ## ###
