### ISSUE TITLE
Linux build error - no rule for /src/encrypt/protoc

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe-archive/MaidSafe#232]
All was well building from the Ubuntu instructions in a clean virtual machine as Mint17.1 until error from make as below:

Linking CXX executable ../../test_routing_multiple_definitions
[ 81%] Built target test_routing_multiple_definitions
make[2]: **\* No rule to make target `/home/orange/MaidSafe/MaidSafe/src/encrypt/protoc', needed by`GeneratedProtoFiles/maidsafe/encrypt/data_map.pb.cc'. Stop.
make[1]: **\* [src/encrypt/CMakeFiles/maidsafe_encrypt.dir/all] Error 2
make: **\* [all] Error 2

Let me know, if there's any more detail from it that might be useful and I can run it again as needed.

**Comment by dallyshalla** [comment]
Just built around the same time as you yesterday on Ubuntu all went well to the end; definitely make sure to 'git checkout next' on each repository manually perhaps; build again;

**Comment by davidpbrown** [comment]
Thanks.. I've done every variation I can think of including the git checkout next, so what the difference is, I don't know. Likely I'm missing something obvious. I'll try again end of week + as it's suggested that this might disappear as an issue next update.

User error: Replace User. Closing.
